export default {
    BINANCE: {
        UPDATE_BUY: 'UPDATE_BUY',
        UPDATE_SELL: 'UPDATE_SELL',
        REMOVE_BUY: 'REMOVE_BUY',
        REMOVE_SELL: 'REMOVE_SELL',
        INITIALIZE_STREAMS: 'INITIALIZE_STREAMS',
        INITIALIZE_ORDERBOOK: 'INITIALIZE_ORDERBOOK'

       },
    
    UPDATE_LISTINGS_BITTREX: 'UPDATE_LISTINGS_BITTREX',
    UPDATE_LISTINGS_UNISWAP: 'UPDATE_LISTINGS_UNISWAP',
    MATCH_LISTING_DEXAG_BITTREX: 'MATCH_LISTING_DEXAG_BITTREX',
    MATCH_LISTING_UNISWAP_BITTREX: 'MATCH_LISTING_UNISWAP_BITTREX',


    ETH_BASE_TRADE: 'ETH_BASE_TRADE',
    ERC20_BASE_TRADE: 'ERC20_BASE_TRADE',

    TRADE_BUYC_SELLD: 'TRADE_BUYC_SELLD',
    TRADE_BUYD_SELLC: 'TRADE_BUYD_SELLC'

}